### ISSUE TITLE
Add support for <polygon>

### ISSUE THREAD

**Issue by dominikwilkowski** [winkerVSbecks/xvg#15]
check out this page:
https://gel.westpacgroup.com.au/resources/plan/

There are plenty SVGs and some don't get outlines inside the same shape:

![screen shot 2017-01-04 at 3 20 23 pm](https://cloud.githubusercontent.com/assets/1266923/21631618/69f4ccf6-d291-11e6-875c-e4a32b6429e8.png)

I had a quick shot at debugging but it also doesn't seem to run in codepen so I gave up.

**Comment by valscion** [comment]
Could it be because those elements are created with `<polygon>`, `<rect>` and `<circle>` elements? As you can see, the circles don't get the outlines either. All the `<path>` elements seem to get outlines correctly on that page when I glanced at it quickly.

**Comment by winkerVSbecks** [comment]
@valscion that is correct. The extension is only targeting `<path>` for now. But I guess extending it to `polygon` would make sense too. I'm not sure if other elements such as`<rect>` & `<circle>` would really benefit from this.

**Comment by valscion** [comment]
Thanks! Maybe the issue title could be changed to something like:

> Implement support for `<polygon>`

That way this issue wouldn't seem like a bug at first glance + it would allow this issue to focus on the smallest task possible.
