### ISSUE TITLE
Add support for SVG documents

### ISSUE THREAD

**Issue by tordans** [winkerVSbecks/xvg#18]
I open an svg from my dropbox and klick the icon in my toolbar. Nothing happens with the SVG but the following error messages shows in the console.

(I cannot share the svg itself unfortunately.)

I then added the same svg in an empty html-doc, which works fine – no errors.

```
Uncaught TypeError: Cannot read property 'appendChild' of null
    at e (xvg.js:2)
    at xvg.js:1
    at xvg.js:1
    at n (xvg.js:1)
    at xvg.js:1
    at xvg.js:1
    at xvg.js:1
    at xvg.js:1
    at Object.<anonymous> (xvg.js:2)
    at n (xvg.js:1)
e @ xvg.js:2
(anonymous) @ xvg.js:1
(anonymous) @ xvg.js:1
n @ xvg.js:1
(anonymous) @ xvg.js:1
(anonymous) @ xvg.js:1
(anonymous) @ xvg.js:1
(anonymous) @ xvg.js:1
(anonymous) @ xvg.js:2
n @ xvg.js:1
(anonymous) @ xvg.js:2
n @ xvg.js:1
(anonymous) @ xvg.js:1
(anonymous) @ xvg.js:1
```

**Comment by winkerVSbecks** [comment]
Sounds like you have the SVG element open instead of an HTML document with embedded SVG. Currently the application doesn't support SVG documents.
