### ISSUE TITLE
Add Chrome extension settings

### ISSUE THREAD

**Issue by SgtSahnig** [winkerVSbecks/xvg#20]
The Possibility to toggle things like zoom-on-hover would be nice. (If this is even a desired effect)

**Comment by winkerVSbecks** [comment]
https://developer.chrome.com/extensions/options

**Comment by SgtSahnig** [comment]
Im sorry, for not being specific enough in my initial post. I meant a little menu opening itself with triggerable options.

**Comment by winkerVSbecks** [comment]
@SgtSahnig I'm working to add extension settings that will allow you to configure everything. I believe Chrome remembers these settings and you won't have to repeat it every time you use the extension. Does that seem acceptable? 


<img width="253" alt="screen shot 2017-01-20 at 10 55 47 am" src="https://cloud.githubusercontent.com/assets/42671/22155887/0e047f48-deff-11e6-9803-3059e5cbe32e.png">
![screen shot 2017-01-20 at 10 55 29 am](https://cloud.githubusercontent.com/assets/42671/22155891/0f3a8e70-deff-11e6-84ba-18cb80e4a53c.png)

**Comment by SgtSahnig** [comment]
It's your project. I just thought that is would be nice if there is a configurable settings window like AddBlockPlus has. Just in case you need to trigger those settings on the fly.

**Comment by winkerVSbecks** [comment]
@SgtSahnig Sounds good. I'll look into that too. 
I know it is my project but, always helps to have some user feedback 😊
