### ISSUE TITLE
Bug: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by djdmsr** [winkerVSbecks/xvg#25]
xvg.js:2 Uncaught TypeError: Cannot read property 'appendChild' of null
    at e (xvg.js:2)
    at xvg.js:1
    at xvg.js:1
    at n (xvg.js:1)
    at xvg.js:1
    at xvg.js:1
    at xvg.js:1
    at xvg.js:1
    at Object.<anonymous> (xvg.js:2)
    at n (xvg.js:1)
e @ xvg.js:2
(anonymous) @ xvg.js:1
(anonymous) @ xvg.js:1
n @ xvg.js:1
(anonymous) @ xvg.js:1
(anonymous) @ xvg.js:1
(anonymous) @ xvg.js:1
(anonymous) @ xvg.js:1
(anonymous) @ xvg.js:2
n @ xvg.js:1
(anonymous) @ xvg.js:2
n @ xvg.js:1
(anonymous) @ xvg.js:1
(anonymous) @ xvg.js:1

**Comment by winkerVSbecks** [comment]
duplicate #18
