### ISSUE TITLE
You were killed on chrome extension website 😬

### ISSUE THREAD

**Issue by kud** [winkerVSbecks/xvg#32]

**Comment by aderchox** [comment]
Yeah this extension is not there anymore :(

**Comment by skj-skj** [comment]
what's the reason?

**Comment by kud** [comment]
Closed without any explanation? That's sad.

**Comment by winkerVSbecks** [comment]
@kud the extension is no longer maintained. Chrome updated its API and since I never updated the extension, it was killed.

**Comment by kud** [comment]
Thank you for the quick answer @winkerVSbecks 😌
